### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by zhang96716** [Jinjiarui/CoRide#2]
Hello, I read your code and paper, very interested, but when I run your code, I found a few files missing‘ algo.cfun ’，‘ algo.cod ’，‘ algo.stdqn ’Can you give me some information? Thank you very much and look forward to your reply

**Comment by Jinjiarui** [comment]
Thanks for your interest in our code. These missing files contain the implementation of our models "algo.cfun"  for CoRide,  "algo.cod" for COD (Cooperative Order Dispatching algorithm), “algo.kl" for KL,  "algo.stdqn" for  spatio-temporal DQN.
CFuN: CoRide: Joint Order Dispatching and Fleet Management for Multi-Scale Ride-Hailing Platforms
KL: Multi-Agent Reinforcement Learning for Order-dispatching via Order-Vehicle Distribution Matching
COD: Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning
STDQN: Deep Reinforcement Learning with Knowledge Transfer for Online Rides Order Dispatching
One can see that all these methods are developed with DiDI AI Labs. Due to the policy of company, we are not able to make these codes public without permission.

**Comment by zhang96716** [comment]
Thank you for your answer. Do you have relevant papers and codes for intensive learning vehicle scheduling and running? It is very difficult for me to reproduce this project, so please help me. If so, can you send it to me?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jinjiarui/CoRide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jinjiarui/CoRide] hello (#2)





 
Thanks for your interest in our code. These missing files contain the implementation of our models "algo.cfun"  for CoRide,  "algo.cod" for COD (Cooperative Order Dispatching algorithm), “algo.kl" for KL,  "algo.stdqn" for  spatio-temporal DQN.
 CFuN: CoRide: Joint Order Dispatching and Fleet Management for Multi-Scale Ride-Hailing Platforms
 KL: Multi-Agent Reinforcement Learning for Order-dispatching via Order-Vehicle Distribution Matching
 COD: Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning
 STDQN: Deep Reinforcement Learning with Knowledge Transfer for Online Rides Order Dispatching
 One can see that all these methods are developed with DiDI AI Labs. Due to the policy of company, we are not able to make these codes public without permission.

**Comment by Jinjiarui** [comment]
For KL paper, it just modified on the traditional DQN methods, which is easy to reproduce. For COD, you can refer to its original paper MFRL (https://arxiv.org/pdf/1802.05438.pdf), . For CoRide, I have established the repository for the paper list of hierarchical RL (https://github.com/Jinjiarui/hrl-papers), and some of these papers have published their codes.

**Comment by zhang96716** [comment]
Thank you for your patience. If you can, can I give you a contact information?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jinjiarui/CoRide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jinjiarui/CoRide] hello (#2)





 
For KL paper, it just modified on the traditional DQN methods, which is easy to reproduce. For COD, you can refer to its original paper MFRL (https://arxiv.org/pdf/1802.05438.pdf), . For CoRide, I have established the repository for the paper list of hierarchical RL (https://github.com/Jinjiarui/hrl-papers), and some of these papers have published their codes.

**Comment by yyds-xtt** [comment]
Now, can the code of these papers be open-sourced？
Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning?

**Comment by yyds-xtt** [comment]
Now, can the code of these papers be open-sourced？
Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning?

**Comment by yyds-xtt** [comment]
Now, can the code of these papers be open-sourced？
Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning?

**Comment by yyds-xtt** [comment]
Now, can the code of these papers be open-sourced？
Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning?

**Comment by Jinjiarui** [comment]
Sorry for the delayed replay. We are not allowed to open-sourced the code of papers by Didi Chuxing due to the company policy. Instead, we will provide some examples of popular RL solutions on order dispatching tasks soon.

**Comment by yyds-xtt** [comment]
你们 什么时候提供在订单调度任务上流行的 RL 解决方案。

**Comment by yyds-xtt** [comment]
你们 什么时候提供在订单调度任务上流行的 RL 解决方案。

**Comment by yyds-xtt** [comment]
你们 什么时候提供在订单调度任务上流行的 RL 解决方案。

**Comment by yyds-xtt** [comment]
你们 什么时候提供在订单调度任务上流行的 RL 解决方案。

**Comment by yyds-xtt** [comment]
你们 什么时候提供在订单调度任务上流行的 RL 解决方案。

**Comment by Jinjiarui** [comment]
Sorry for the delayed feedbacks. We have released DQN method for order dispatching and fleet management tasks at https://github.com/Jinjiarui/CoRide/blob/main/algo/il/dqn.py

**Comment by yyds-xtt** [comment]
涉及多智能体方法的有吗
2647790445@qq.com

**Comment by yyds-xtt** [comment]
涉及多智能体方法的有吗
[2647790445@qq.com](mailto:2647790445@qq.com)

**Comment by yyds-xtt** [comment]
涉及多智能体方法的有吗
[2647790445@qq.com](mailto:2647790445@qq.com)

**Comment by yyds-xtt** [comment]
例如这个 Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning

**Comment by yyds-xtt** [comment]
多智能的有吗



---Original---
From: ***@***.***&gt;
Date: Fri, Feb 25, 2022 19:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jinjiarui/CoRide] hello (#2)




 
Sorry for the delayed feedbacks. We have released DQN method for order dispatching and fleet management tasks at https://github.com/Jinjiarui/CoRide/blob/main/algo/il/dqn.py
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jinjiarui** [comment]
Sorry, we are not able to provide those algorithms developed in the collaborations with DiDi Chuxing, due to the policy of the company.

**Comment by yyds-xtt** [comment]
多久了，还不能公布，

**Comment by Jinjiarui** [comment]
We have released all the codes that we have permission to open-source.

**Comment by yyds-xtt** [comment]
Efficient Ridesharing Order Dispatching with
Mean Field Multi-Agent Reinforcement Learning，2647790445@qq.com，能否发一份不涉及隐私数据的代码，参考一下。

**Comment by Jinjiarui** [comment]
We are not allowed to do that. Please contact the main authors of Efficient Ridesharing Order Dispatching with Mean Field Multi-Agent Reinforcement Learning for the code.
